### ISSUE TITLE
Yaml to Agent - Angle issue

### ISSUE THREAD

**Issue by michabay05** [kenblu24/RobotSwarmSimulator#18]
### Problem
Setting a world using a yaml file, I created a single agent and set its angle is set to 0.5pi radians. (The unit for this is radians; see definition below.)
https://github.com/kenblu24/RobotSwarmSimulator/blob/30d3237ed7c463f07010e7bc8dea07b26a9be79e/src/swarmsim/agent/Agent.py#L95-L96

However, when running the simulator, I get the image below. The agent should be looking upward rather than downwards.

<img src="https://github.com/user-attachments/assets/7efcafda-1213-48b7-922a-c6649f2c0691" width=75% />

Given that I have set things up correctly, this could either be a simulator issue or a rendering bug. I suspect (and *hope*) this is a simple rendering bug. 

---

### Minimal Reproducible Example
Using from the `main` branch.
<details>
<summary>world_setup.yaml</summary>

```yaml
type: "RectangularWorld"
size: [5, 5]
time_step: !np 1 / 40
agents:
    - type: "MazeAgent"
      position: [2.5, 2.5]
      angle: !np pi * 0.5
      agent_radius: 0.175
      sensors:
          - type: "BinaryFOVSensor"
            theta: 0.45
            distance: 1
```
</details>

<details>
<summary>demo.py</summary>

```python
from swarmsim.world.simulate import main
from swarmsim.world.RectangularWorld import RectangularWorldConfig

world_config = RectangularWorldConfig.from_yaml("world_setup.yaml")

main(world_config, start_paused=True)
```
</details>
